"""
API Pydantic Models

Request and response models for all API endpoints.
"""
from .common import (
    ErrorResponse,
    SuccessResponse,
)
from .agent_models import (
    AgentCommandRequest,
    AgentListResponse,
    AgentLogsResponse,
    AgentMetricsResponse,
    AgentOperationResponse,
    AgentStatusResponse,
    CommandResponse,
)
from .forecast_models import (
    ForecastAccuracyResponse,
    ForecastListResponse,
    ForecastResponse,
    GenerateForecastRequest,
    GenerateForecastResponse,
    LatestForecastsResponse,
)
from .market_data_models import (
    MarketDataListResponse,
    MarketDataResponse,
    StreamControlRequest,
    StreamControlResponse,
    SymbolInfoResponse,
    SymbolListResponse,
)
from .performance_models import (
    PerformanceByStrategyResponse,
    PerformanceChartResponse,
    PerformanceMetricsResponse as TradingPerformanceMetricsResponse,
    PerformanceSummaryResponse,
    MonthlyPerformanceResponse,
)
from .strategy_models import (
    StrategyListResponse,
    StrategyOperationResponse,
    StrategyPerformanceResponse,
    StrategyResponse,
    StrategyUpdateResponse,
    UpdateStrategyRequest,
)
from .system_models import (
    ComponentHealthListResponse,
    EmergencyStopRequest,
    EmergencyStopResponse,
    HealthCheckResponse,
    RestartRequest,
    RestartResponse,
    SystemStatusResponse,
)
from .trading_models import (
    AccountResponse,
    ClosePositionRequest,
    ClosePositionResponse,
    OrderResponse,
    PlaceOrderRequest,
    PositionListResponse,
    PositionResponse,
    TradingHistoryListResponse,
    TradingHistoryResponse,
)
from .backtesting_models import (
    BacktestConfigListResponse,
    BacktestConfigResponse,
    BacktestRunResponse,
    BacktestRunStatusResponse,
    CancelRunResponse,
    CompareRunsRequest,
    CompareRunsResponse,
    CreateBacktestConfigRequest,
    CreateParameterGridRequest,
    ErrorDetail,
    ErrorResponse as BacktestErrorResponse,
    ExecuteParameterGridRequest,
    ExecutionMode,
    MetricsComparisonResponse,
    OptimizationResultResponse,
    ParameterGridResponse,
    ParameterGridResultsResponse,
    PerformanceMetricsResponse as BacktestPerformanceMetricsResponse,
    RunBacktestRequest,
    RunStatus,
    SimulatedTradeResponse,
    StatisticalTestResponse,
    TradeAction,
    TradeListResponse,
    TradeOverlapResponse,
    ValidationResultResponse,
)

__all__ = [
    # Common models
    "ErrorResponse",
    "SuccessResponse",
    # Agent models
    "AgentCommandRequest",
    "AgentListResponse",
    "AgentLogsResponse",
    "AgentMetricsResponse",
    "AgentOperationResponse",
    "AgentStatusResponse",
    "CommandResponse",
    # Forecast models
    "ForecastAccuracyResponse",
    "ForecastListResponse",
    "ForecastResponse",
    "GenerateForecastRequest",
    "GenerateForecastResponse",
    "LatestForecastsResponse",
    # Market data models
    "MarketDataListResponse",
    "MarketDataResponse",
    "StreamControlRequest",
    "StreamControlResponse",
    "SymbolInfoResponse",
    "SymbolListResponse",
    # Performance models
    "PerformanceByStrategyResponse",
    "PerformanceChartResponse",
    "TradingPerformanceMetricsResponse",
    "PerformanceSummaryResponse",
    "MonthlyPerformanceResponse",
    # Strategy models
    "StrategyListResponse",
    "StrategyOperationResponse",
    "StrategyPerformanceResponse",
    "StrategyResponse",
    "StrategyUpdateResponse",
    "UpdateStrategyRequest",
    # System models
    "ComponentHealthListResponse",
    "EmergencyStopRequest",
    "EmergencyStopResponse",
    "HealthCheckResponse",
    "RestartRequest",
    "RestartResponse",
    "SystemStatusResponse",
    # Trading models
    "AccountResponse",
    "ClosePositionRequest",
    "ClosePositionResponse",
    "OrderResponse",
    "PlaceOrderRequest",
    "PositionListResponse",
    "PositionResponse",
    "TradingHistoryListResponse",
    "TradingHistoryResponse",
    # Backtesting models
    "BacktestConfigListResponse",
    "BacktestConfigResponse",
    "BacktestRunResponse",
    "BacktestRunStatusResponse",
    "CancelRunResponse",
    "CompareRunsRequest",
    "CompareRunsResponse",
    "CreateBacktestConfigRequest",
    "CreateParameterGridRequest",
    "ErrorDetail",
    "BacktestErrorResponse",
    "ExecuteParameterGridRequest",
    "ExecutionMode",
    "MetricsComparisonResponse",
    "OptimizationResultResponse",
    "ParameterGridResponse",
    "ParameterGridResultsResponse",
    "BacktestPerformanceMetricsResponse",
    "RunBacktestRequest",
    "RunStatus",
    "SimulatedTradeResponse",
    "StatisticalTestResponse",
    "TradeAction",
    "TradeListResponse",
    "TradeOverlapResponse",
    "ValidationResultResponse",
]
